export const erpRoles = [
  {
    name: "Super Admin",
    scope: "Full platform ownership",
    permissions: ["all_modules", "user_management", "audit_logs", "system_config"],
  },
  {
    name: "Sales Executive",
    scope: "Lead calling, follow-ups, proposals",
    permissions: ["view_assigned_leads", "update_lead_status", "create_call_logs"],
  },
  {
    name: "Team Leader",
    scope: "Team allocation and performance monitoring",
    permissions: ["reassign_leads", "team_reports", "follow_up_escalations"],
  },
  {
    name: "Backend Executive",
    scope: "Service delivery and document workflows",
    permissions: ["service_cases", "documents", "client_communication"],
  },
  {
    name: "Accounts",
    scope: "Invoices, payments, collections",
    permissions: ["payments", "invoices", "finance_reports"],
  },
  {
    name: "HR",
    scope: "Employee records and attendance",
    permissions: ["employee_profiles", "attendance", "leave_management"],
  },
  {
    name: "Management",
    scope: "Executive dashboards and analytics",
    permissions: ["reports", "dashboards", "audit_read"],
  },
]

export const departments = [
  {
    id: "funding",
    name: "Funding",
    branch: "Delhi NCR",
    routeKeywords: ["funding", "vc", "loan", "investor", "seed", "cgtmse", "pmegp"],
    seniorOwner: "Senior Funding Manager",
    dailyCapacity: 35,
  },
  {
    id: "compliance",
    name: "Compliance",
    branch: "Noida",
    routeKeywords: ["gst", "iso", "startup india", "compliance", "filing", "certification"],
    seniorOwner: "Compliance Team Lead",
    dailyCapacity: 45,
  },
  {
    id: "incorporation",
    name: "Company Incorporation",
    branch: "Noida",
    routeKeywords: ["company", "incorporation", "registration", "cin", "startup"],
    seniorOwner: "Incorporation Lead",
    dailyCapacity: 30,
  },
  {
    id: "digital-growth",
    name: "Digital Growth",
    branch: "Remote",
    routeKeywords: ["website", "digital marketing", "seo", "ads", "branding"],
    seniorOwner: "Growth Services Lead",
    dailyCapacity: 25,
  },
]

export const leadSources = [
  "Website forms",
  "Meta ads",
  "Google ads",
  "LinkedIn",
  "IndiaMART",
  "Referrals",
  "Manual entry",
  "Excel/CSV import",
]

export const leadStatuses = [
  "New",
  "Attempted",
  "Connected",
  "Interested",
  "Follow-up",
  "Proposal Sent",
  "Documentation Pending",
  "Negotiation",
  "Converted",
  "Not Interested",
  "Invalid",
  "Dropped",
]

export const leadFields = [
  "Lead ID",
  "Name",
  "Company Name",
  "Mobile Number",
  "Email",
  "City",
  "State",
  "Industry",
  "Business Type",
  "Requirement",
  "Service Interested",
  "Lead Source",
  "Priority",
  "Assigned Employee",
  "Status",
  "Follow-up Date",
  "Notes",
  "Uploaded Documents",
  "Timestamp",
]

export const services = [
  "Company incorporation",
  "GST registration",
  "ISO certification",
  "Startup India",
  "VC funding",
  "Loan processing",
  "Compliance filing",
  "Digital marketing services",
  "Website development",
]

export const serviceWorkflows = [
  {
    name: "VC funding",
    slaDays: 45,
    stages: [
      "Document collection",
      "Financial review",
      "Pitch deck preparation",
      "Due diligence",
      "Investor connection",
      "Agreement signing",
      "Fund disbursement",
    ],
  },
  {
    name: "GST registration",
    slaDays: 7,
    stages: ["KYC collection", "Application drafting", "Government submission", "ARN tracking", "Certificate delivery"],
  },
  {
    name: "Company incorporation",
    slaDays: 15,
    stages: ["Name approval", "DSC/DIN", "MOA/AOA drafting", "ROC filing", "CIN handover"],
  },
  {
    name: "Digital marketing services",
    slaDays: 30,
    stages: ["Discovery", "Campaign plan", "Asset creation", "Launch", "Performance review"],
  },
]

export const sampleEmployees = [
  {
    id: "emp-101",
    name: "Aarav Mehta",
    role: "Sales Executive",
    departmentId: "funding",
    branch: "Delhi NCR",
    seniority: "senior",
    activeLeadCount: 22,
    todayCalls: 48,
    conversionRate: 31,
  },
  {
    id: "emp-102",
    name: "Nisha Rao",
    role: "Sales Executive",
    departmentId: "compliance",
    branch: "Noida",
    seniority: "mid",
    activeLeadCount: 17,
    todayCalls: 42,
    conversionRate: 27,
  },
  {
    id: "emp-103",
    name: "Kabir Sethi",
    role: "Team Leader",
    departmentId: "incorporation",
    branch: "Noida",
    seniority: "senior",
    activeLeadCount: 12,
    todayCalls: 32,
    conversionRate: 34,
  },
  {
    id: "emp-104",
    name: "Priya Nair",
    role: "Backend Executive",
    departmentId: "digital-growth",
    branch: "Remote",
    seniority: "mid",
    activeLeadCount: 9,
    todayCalls: 18,
    conversionRate: 19,
  },
]

export const sampleLeads = [
  {
    id: "GVL-2026-001",
    name: "Rohan Sharma",
    companyName: "Rohan Foods LLP",
    mobile: "+91 98109 24009",
    email: "rohan@example.com",
    city: "Delhi",
    state: "Delhi",
    industry: "Food processing",
    businessType: "LLP",
    requirement: "CGTMSE loan and GST registration",
    serviceInterested: "Loan processing",
    source: "Website forms",
    priority: "High",
    assignedEmployeeId: "emp-101",
    status: "Follow-up",
    followUpDate: "2026-05-16",
    notes: "Requested funding eligibility call and document checklist.",
    timestamp: "2026-05-15T09:10:00.000Z",
  },
  {
    id: "GVL-2026-002",
    name: "Meera Gupta",
    companyName: "GreenLabs Private Limited",
    mobile: "+91 90000 11111",
    email: "meera@example.com",
    city: "Noida",
    state: "Uttar Pradesh",
    industry: "Clean technology",
    businessType: "Private Limited",
    requirement: "Startup India recognition and VC funding",
    serviceInterested: "VC funding",
    source: "LinkedIn",
    priority: "Critical",
    assignedEmployeeId: "emp-101",
    status: "Proposal Sent",
    followUpDate: "2026-05-15",
    notes: "High-value funding lead routed to senior sales manager.",
    timestamp: "2026-05-14T12:30:00.000Z",
  },
  {
    id: "GVL-2026-003",
    name: "Ankit Jain",
    companyName: "Jain Imports",
    mobile: "+91 82222 33333",
    email: "ankit@example.com",
    city: "Ghaziabad",
    state: "Uttar Pradesh",
    industry: "Trading",
    businessType: "Proprietorship",
    requirement: "GST and ISO certification",
    serviceInterested: "GST registration",
    source: "Google ads",
    priority: "Medium",
    assignedEmployeeId: "emp-102",
    status: "Connected",
    followUpDate: "2026-05-17",
    notes: "Shared GST quotation.",
    timestamp: "2026-05-14T15:45:00.000Z",
  },
]

export const sampleClients = [
  {
    id: "GVC-2026-014",
    name: "GreenLabs Private Limited",
    cin: "U72900UP2025PTC000014",
    gst: "09ABCDE1234F1Z5",
    pan: "ABCDE1234F",
    directors: ["Meera Gupta", "Sahil Gupta"],
    assignedBackendExecutive: "Priya Nair",
    activeServices: ["VC funding", "Startup India"],
    paymentStatus: "Partially paid",
    serviceStatus: "Due diligence",
  },
]

export const dashboardMetrics = [
  { label: "Open leads", value: "486", helper: "+18 today", tone: "orange" },
  { label: "Pending follow-ups", value: "73", helper: "14 overdue", tone: "red" },
  { label: "Converted clients", value: "128", helper: "26.3% conversion", tone: "green" },
  { label: "Monthly revenue", value: "₹42.8L", helper: "service-wise tracked", tone: "blue" },
]

export const automationRules = [
  "Follow-up reminders before due time and missed follow-up alerts after SLA breach",
  "Duplicate detection across mobile, email, company name, and GST/PAN once available",
  "Auto reassignment when no activity is logged within the configured department SLA",
  "Payment reminders for due invoices and partial collections",
  "Compliance due-date alerts for filings, renewals, certificates, and agreements",
  "Daily sales, backend SLA, collections, and management reports",
]

export const databaseTables = [
  "users",
  "employees",
  "departments",
  "branches",
  "roles",
  "permissions",
  "leads",
  "lead_activities",
  "lead_assignments",
  "clients",
  "client_contacts",
  "services",
  "service_cases",
  "service_case_stages",
  "tasks",
  "documents",
  "document_versions",
  "payments",
  "invoices",
  "agreements",
  "call_logs",
  "notifications",
  "tickets",
  "attendance",
  "leave_requests",
  "reports",
  "audit_logs",
  "login_activities",
]
